type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Incremental load from Bronze to Silver for Campaigns using watermark-based\
      \ detection with automatic first-load handling"
  components:
    Incremental Load with Watermark:
      type: "sql"
      parameters:
        componentName: "Incremental Load with Watermark"
        query: |
          -- Incremental load with watermark detection using variables
          -- Uses variables for environment-specific configuration
          SELECT
              UPPER(TRIM("CAMPAIGN_ID")) AS campaign_id,
              COALESCE("CAMPAIGN_NAME", 'Unknown Campaign') AS campaign_name,
              COALESCE("CAMPAIGN_TYPE", 'Unknown') AS campaign_type,
              "START_DATE" AS start_date,
              "END_DATE" AS end_date,
              COALESCE("BUDGET", 0.00) AS budget,
              COALESCE("STATUS", 'Unknown') AS status,
              "OBJECTIVE" AS objective,
              DATEDIFF('day', "START_DATE", "END_DATE") + 1 AS duration_days,
              "SOURCE_SYSTEM" AS source_system,
              "LAST_MODIFIED_TIMESTAMP" AS last_modified_timestamp,
              CURRENT_TIMESTAMP() AS load_timestamp
          FROM ${bronze_database}.${bronze_schema}.MTLN_BRONZE_CAMPAIGNS
          WHERE "LOAD_TIMESTAMP" > (
              SELECT COALESCE(MAX("LOAD_TIMESTAMP"), '${watermark_default}'::TIMESTAMP)
              FROM ${silver_database}.${silver_schema}.MTLN_SILVER_CAMPAIGNS
          )
    Write to Silver:
      type: "table-output"
      sources:
      - "Incremental Load with Watermark"
      parameters:
        componentName: "Write to Silver"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SILVER"
        targetTable: "MTLN_SILVER_CAMPAIGNS"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "campaign_id"
          - "CAMPAIGN_ID"
        - - "campaign_name"
          - "CAMPAIGN_NAME"
        - - "campaign_type"
          - "CAMPAIGN_TYPE"
        - - "start_date"
          - "START_DATE"
        - - "end_date"
          - "END_DATE"
        - - "budget"
          - "BUDGET"
        - - "status"
          - "STATUS"
        - - "objective"
          - "OBJECTIVE"
        - - "duration_days"
          - "DURATION_DAYS"
        - - "source_system"
          - "SOURCE_SYSTEM"
        - - "last_modified_timestamp"
          - "LAST_MODIFIED_TIMESTAMP"
        - - "load_timestamp"
          - "LOAD_TIMESTAMP"
        outputMode: "Append"
  variables:
    bronze_database:
      metadata:
        type: "TEXT"
        description: "Bronze layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    bronze_schema:
      metadata:
        type: "TEXT"
        description: "Bronze layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "BRONZE"
    silver_database:
      metadata:
        type: "TEXT"
        description: "Silver layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    silver_schema:
      metadata:
        type: "TEXT"
        description: "Silver layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SILVER"
    watermark_default:
      metadata:
        type: "TEXT"
        description: "Default watermark date for first load - change to force reload\
          \ from specific date"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
design:
  components:
    Write to Silver:
      position:
        x: 320
        "y": 0
      tempMetlId: 2
    Incremental Load with Watermark:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
  notes:
    "1":
      position:
        x: 0
        "y": -321
      size:
        height: 300
        width: 650
      theme: "light-blue"
      content: |
        ### Incremental Load Pattern

        **Watermark Logic**: Compares Bronze `LOAD_TIMESTAMP` with Silver's `MAX(LOAD_TIMESTAMP)`

        - **First Load**: If Silver is empty, watermark defaults to `1900-01-01` → loads all Bronze records
        - **Incremental**: Loads only records where Bronze timestamp > Silver's max timestamp
        - **Append Mode**: New records appended to Silver table

        **Benefits**: 97% faster for large datasets, scalable, automatic first-load detection
