type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Incremental load from Bronze to Silver for Channels using watermark-based\
      \ detection with automatic first-load handling"
  components:
    Incremental Load with Watermark:
      type: "sql"
      parameters:
        componentName: "Incremental Load with Watermark"
        query: |
          -- Incremental load with watermark detection using variables
          SELECT
              UPPER(TRIM("CHANNEL_ID")) AS channel_id,
              COALESCE("CHANNEL_NAME", 'Unknown Channel') AS channel_name,
              COALESCE("CHANNEL_TYPE", 'Unknown') AS channel_type,
              COALESCE("CATEGORY", 'Uncategorized') AS category,
              "COST_STRUCTURE" AS cost_structure,
              "SOURCE_SYSTEM" AS source_system,
              "LAST_MODIFIED_TIMESTAMP" AS last_modified_timestamp,
              CURRENT_TIMESTAMP() AS load_timestamp
          FROM ${bronze_database}.${bronze_schema}.MTLN_BRONZE_CHANNELS
          WHERE "LOAD_TIMESTAMP" > (
              SELECT COALESCE(MAX("LOAD_TIMESTAMP"), '${watermark_default}'::TIMESTAMP)
              FROM ${silver_database}.${silver_schema}.MTLN_SILVER_CHANNELS
          )
    Write to Silver:
      type: "table-output"
      sources:
      - "Incremental Load with Watermark"
      parameters:
        componentName: "Write to Silver"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SILVER"
        targetTable: "MTLN_SILVER_CHANNELS"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "channel_id"
          - "CHANNEL_ID"
        - - "channel_name"
          - "CHANNEL_NAME"
        - - "channel_type"
          - "CHANNEL_TYPE"
        - - "category"
          - "CATEGORY"
        - - "cost_structure"
          - "COST_STRUCTURE"
        - - "source_system"
          - "SOURCE_SYSTEM"
        - - "last_modified_timestamp"
          - "LAST_MODIFIED_TIMESTAMP"
        - - "load_timestamp"
          - "LOAD_TIMESTAMP"
        outputMode: "Append"
  variables:
    bronze_database:
      metadata:
        type: "TEXT"
        description: "Bronze layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    bronze_schema:
      metadata:
        type: "TEXT"
        description: "Bronze layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "BRONZE"
    silver_database:
      metadata:
        type: "TEXT"
        description: "Silver layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    silver_schema:
      metadata:
        type: "TEXT"
        description: "Silver layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SILVER"
    watermark_default:
      metadata:
        type: "TEXT"
        description: "Default watermark date for first load - change to force reload\
          \ from specific date"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
design:
  components:
    Incremental Load with Watermark:
      position:
        x: 0
        "y": 0
      tempMetlId: null
    Write to Silver:
      position:
        x: 320
        "y": 0
      tempMetlId: null
  notes:
    "1":
      position:
        x: 0
        "y": -335
      size:
        height: 315
        width: 650
      theme: "light-yellow"
      content: |
        ### Incremental Load - Channels (20 rows, Reference Data)

        **Watermark**: Bronze `LOAD_TIMESTAMP` > Silver `MAX(LOAD_TIMESTAMP)`

        - **First Load**: Empty table → loads all 20 channel records
        - **Incremental**: Only changed channels (rare, reference data)
        - **Quality**: Standardization, category defaults

        **Volume**: Small (20 rows), changes infrequent, subsecond execution
