type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Incremental load from Bronze to Silver for Performance metrics using\
      \ watermark-based detection - HIGH VOLUME table (50K rows)"
  components:
    Incremental Load with Watermark:
      type: "sql"
      parameters:
        componentName: "Incremental Load with Watermark"
        query: "-- Incremental load with watermark detection using variables (HIGH\
          \ VOLUME)\nSELECT\n    UPPER(TRIM(\"PERFORMANCE_ID\")) AS performance_id,\n\
          \    UPPER(TRIM(\"CAMPAIGN_ID\")) AS campaign_id,\n    UPPER(TRIM(\"CHANNEL_ID\"\
          )) AS channel_id,\n    \"PERFORMANCE_DATE\" AS performance_date,\n    COALESCE(\"\
          IMPRESSIONS\", 0) AS impressions,\n    COALESCE(\"CLICKS\", 0) AS clicks,\n\
          \    COALESCE(\"COST\", 0.00) AS cost,\n    COALESCE(\"CONVERSIONS\", 0)\
          \ AS conversions,\n    COALESCE(\"REVENUE\", 0.00) AS revenue,\n    -- Derived\
          \ metrics with validation\n    CASE \n        WHEN COALESCE(\"CLICKS\",\
          \ 0) > COALESCE(\"IMPRESSIONS\", 0) \n        THEN COALESCE(\"IMPRESSIONS\"\
          , 0)\n        ELSE COALESCE(\"CLICKS\", 0)\n    END AS clicks_valid,\n \
          \   CASE \n        WHEN COALESCE(\"IMPRESSIONS\", 0) > 0 \n        THEN\
          \ (COALESCE(\"CLICKS\", 0)::FLOAT / \"IMPRESSIONS\") * 100\n        ELSE\
          \ 0\n    END AS ctr,\n    CASE \n        WHEN COALESCE(\"COST\", 0) > 0\
          \ \n        THEN COALESCE(\"REVENUE\", 0) / \"COST\"\n        ELSE 0\n \
          \   END AS roas,\n    \"SOURCE_SYSTEM\" AS source_system,\n    \"LAST_MODIFIED_TIMESTAMP\"\
          \ AS last_modified_timestamp,\n    CURRENT_TIMESTAMP() AS load_timestamp\n\
          FROM ${bronze_database}.${bronze_schema}.MTLN_BRONZE_PERFORMANCE\nWHERE\
          \ \"LOAD_TIMESTAMP\" > (\n    SELECT COALESCE(MAX(\"LOAD_TIMESTAMP\"), '${watermark_default}'::TIMESTAMP)\n\
          \    FROM ${silver_database}.${silver_schema}.MTLN_SILVER_PERFORMANCE\n\
          )\n"
    Write to Silver:
      type: "table-output"
      sources:
      - "Incremental Load with Watermark"
      parameters:
        componentName: "Write to Silver"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SILVER"
        targetTable: "MTLN_SILVER_PERFORMANCE"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "PERFORMANCE_ID"
          - "PERFORMANCE_ID"
        - - "CAMPAIGN_ID"
          - "CAMPAIGN_ID"
        - - "CHANNEL_ID"
          - "CHANNEL_ID"
        - - "PERFORMANCE_DATE"
          - "PERFORMANCE_DATE"
        - - "IMPRESSIONS"
          - "IMPRESSIONS"
        - - "CLICKS"
          - "CLICKS"
        - - "COST"
          - "COST"
        - - "CONVERSIONS"
          - "CONVERSIONS"
        - - "REVENUE"
          - "REVENUE"
        - - "CLICKS_VALID"
          - "CLICKS_VALID"
        - - "CTR"
          - "CTR"
        - - "ROAS"
          - "ROAS"
        - - "SOURCE_SYSTEM"
          - "SOURCE_SYSTEM"
        - - "LAST_MODIFIED_TIMESTAMP"
          - "LAST_MODIFIED_TIMESTAMP"
        - - "LOAD_TIMESTAMP"
          - "LOAD_TIMESTAMP"
        outputMode: "Append"
  variables:
    bronze_database:
      metadata:
        type: "TEXT"
        description: "Bronze layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    bronze_schema:
      metadata:
        type: "TEXT"
        description: "Bronze layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "BRONZE"
    silver_database:
      metadata:
        type: "TEXT"
        description: "Silver layer database name - override for different environments"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    silver_schema:
      metadata:
        type: "TEXT"
        description: "Silver layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SILVER"
    watermark_default:
      metadata:
        type: "TEXT"
        description: "Default watermark date for first load - change to force reload\
          \ from specific date"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
design:
  components:
    Write to Silver:
      position:
        x: 320
        "y": 0
      tempMetlId: 2
    Incremental Load with Watermark:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
  notes:
    "1":
      position:
        x: -110
        "y": -280
      size:
        height: 275
        width: 650
      theme: "yellow"
      content: |
        ### Incremental Load - Performance (50K rows, HIGH VOLUME)

        **Watermark**: Bronze `LOAD_TIMESTAMP` > Silver `MAX(LOAD_TIMESTAMP)`

        - **First Load**: 50,000 performance records (full historical)
        - **Incremental**: ~500-1000 daily records (critical for performance)
        - **Quality**: Click validation (clicks ≤ impressions), CTR & ROAS calculation
        - **Metrics**: Derives CTR (Click-Through Rate) and ROAS (Return on Ad Spend)

        **Performance**: 97% faster incremental vs full refresh, <5 sec daily loads
