type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "DIM_PRODUCT - SCD Type 1 using Table Update component (overwrite\
      \ changes)"
  components:
    Load Silver Products:
      type: "table-input"
      parameters:
        componentName: "Load Silver Products"
        database: "[Environment Default]"
        schema: "SILVER"
        targetTable: "MTLN_SILVER_PRODUCTS"
        columnNames:
        - "PRODUCT_ID"
        - "SKU"
        - "PRODUCT_NAME"
        - "CATEGORY"
        - "SUBCATEGORY"
        - "BRAND"
        - "PRODUCT_STATUS"
        - "UNIT_PRICE"
        - "COST"
        - "MARGIN"
        - "MARGIN_PERCENT"
        - "SOURCE_SYSTEM"
    Add Timestamps:
      type: "calculator"
      sources:
      - "Load Silver Products"
      parameters:
        componentName: "Add Timestamps"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "UPDATED_TIMESTAMP"
    Update DIM_PRODUCT:
      type: "table-update"
      sources:
      - "Add Timestamps"
      parameters:
        componentName: "Update DIM_PRODUCT"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "${gold_schema}"
        targetTable: "DIM_PRODUCT"
        targetAlias: "target"
        sourceAlias: "source"
        joinExpression:
        - - "\"target\".\"PRODUCT_ID\" = \"source\".\"PRODUCT_ID\""
          - "Case"
        updateMapping:
        - - "SKU"
          - "SKU"
        - - "PRODUCT_NAME"
          - "PRODUCT_NAME"
        - - "CATEGORY"
          - "CATEGORY"
        - - "SUBCATEGORY"
          - "SUBCATEGORY"
        - - "BRAND"
          - "BRAND"
        - - "PRODUCT_STATUS"
          - "PRODUCT_STATUS"
        - - "UNIT_PRICE"
          - "UNIT_PRICE"
        - - "COST"
          - "COST"
        - - "MARGIN"
          - "MARGIN"
        - - "MARGIN_PERCENT"
          - "MARGIN_PERCENT"
        - - "UPDATED_TIMESTAMP"
          - "UPDATED_TIMESTAMP"
        - - "SOURCE_SYSTEM"
          - "SOURCE_SYSTEM"
        includeNotMatched: "Yes"
        insertMapping:
        - - "PRODUCT_ID"
          - "PRODUCT_ID"
        - - "SKU"
          - "SKU"
        - - "PRODUCT_NAME"
          - "PRODUCT_NAME"
        - - "CATEGORY"
          - "CATEGORY"
        - - "SUBCATEGORY"
          - "SUBCATEGORY"
        - - "BRAND"
          - "BRAND"
        - - "PRODUCT_STATUS"
          - "PRODUCT_STATUS"
        - - "UNIT_PRICE"
          - "UNIT_PRICE"
        - - "COST"
          - "COST"
        - - "MARGIN"
          - "MARGIN"
        - - "MARGIN_PERCENT"
          - "MARGIN_PERCENT"
        - - "UPDATED_TIMESTAMP"
          - "CREATED_TIMESTAMP"
        - - "UPDATED_TIMESTAMP"
          - "UPDATED_TIMESTAMP"
        - - "SOURCE_SYSTEM"
          - "SOURCE_SYSTEM"
  variables:
    gold_schema:
      metadata:
        type: "TEXT"
        description: "Gold layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "GOLD"
design:
  components:
    Update DIM_PRODUCT:
      position:
        x: 320
        "y": 0
      tempMetlId: 3
    Add Timestamps:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
    Load Silver Products:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
  notes:
    "1":
      position:
        x: -10
        "y": -400
      size:
        height: 380
        width: 580
      theme: "white"
      content: |
        ### DIM_PRODUCT - SCD Type 1 (Table Update)

        **LOAD STRATEGY**: SCD Type 1 - Overwrite changes (no history)
        **RUN**: Daily

        **Component Flow**:
        1. **Load Silver** - 2,000 products
        2. **Add Timestamps** - UPDATED_TIMESTAMP = NOW
        3. **Table Update** - MERGE operation:
           - **WHEN MATCHED**: UPDATE all columns (overwrites)
           - **WHEN NOT MATCHED**: INSERT new products

        **Match Key**: PRODUCT_ID
        **Surrogate Key**: PRODUCT_KEY (auto-generated by IDENTITY)

        **Result**: Products always show current state, no history tracking

        **Use Case**: Product attributes don't need historical tracking
