type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Load FACT_CAMPAIGN_DAILY - Pre-aggregated campaign performance by\
      \ day with incremental loading"
  components:
    Incremental Load and Aggregate:
      type: "sql"
      parameters:
        componentName: "Incremental Load and Aggregate"
        query: "-- Pre-aggregate campaign performance by campaign and day\nSELECT\n\
          \    c.CAMPAIGN_KEY,\n    d.DATE_KEY,\n    SUM(p.IMPRESSIONS) AS TOTAL_IMPRESSIONS,\n\
          \    SUM(p.CLICKS) AS TOTAL_CLICKS,\n    SUM(p.CONVERSIONS) AS TOTAL_CONVERSIONS,\n\
          \    SUM(p.COST) AS TOTAL_COST,\n    SUM(p.REVENUE) AS TOTAL_REVENUE,\n\
          \    AVG(p.CTR) AS AVG_CTR,\n    AVG(CASE WHEN p.CLICKS > 0 THEN p.COST\
          \ / p.CLICKS ELSE 0 END) AS AVG_CPC,\n    CASE \n        WHEN SUM(p.COST)\
          \ > 0 THEN SUM(p.REVENUE) / SUM(p.COST)\n        ELSE 0 \n    END AS TOTAL_ROAS,\n\
          \    COUNT(DISTINCT p.CHANNEL_ID) AS CHANNEL_COUNT,\n    CURRENT_TIMESTAMP()\
          \ AS LOAD_TIMESTAMP\nFROM ${silver_database}.${silver_schema}.MTLN_SILVER_PERFORMANCE\
          \ p\nINNER JOIN ${gold_database}.${gold_schema}.DIM_CAMPAIGN c\n    ON p.CAMPAIGN_ID\
          \ = c.CAMPAIGN_ID AND c.IS_CURRENT = TRUE\nINNER JOIN ${gold_database}.${gold_schema}.DIM_DATE\
          \ d\n    ON TO_NUMBER(TO_CHAR(p.PERFORMANCE_DATE, 'YYYYMMDD')) = d.DATE_KEY\n\
          WHERE p.LOAD_TIMESTAMP > (\n    SELECT COALESCE(MAX(LOAD_TIMESTAMP), '${watermark_default}'::TIMESTAMP)\n\
          \    FROM ${gold_database}.${gold_schema}.FACT_CAMPAIGN_DAILY\n)\nGROUP\
          \ BY\n    c.CAMPAIGN_KEY,\n    d.DATE_KEY\n"
    Write to FACT_CAMPAIGN_DAILY:
      type: "table-output"
      sources:
      - "Incremental Load and Aggregate"
      parameters:
        componentName: "Write to FACT_CAMPAIGN_DAILY"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "${gold_schema}"
        targetTable: "FACT_CAMPAIGN_DAILY"
        outputMode: "Append"
        columnMapping:
        - - "CAMPAIGN_KEY"
          - "CAMPAIGN_KEY"
        - - "DATE_KEY"
          - "DATE_KEY"
        - - "TOTAL_IMPRESSIONS"
          - "TOTAL_IMPRESSIONS"
        - - "TOTAL_CLICKS"
          - "TOTAL_CLICKS"
        - - "TOTAL_CONVERSIONS"
          - "TOTAL_CONVERSIONS"
        - - "TOTAL_COST"
          - "TOTAL_COST"
        - - "TOTAL_REVENUE"
          - "TOTAL_REVENUE"
        - - "AVG_CTR"
          - "AVG_CTR"
        - - "AVG_CPC"
          - "AVG_CPC"
        - - "TOTAL_ROAS"
          - "TOTAL_ROAS"
        - - "CHANNEL_COUNT"
          - "CHANNEL_COUNT"
        - - "LOAD_TIMESTAMP"
          - "LOAD_TIMESTAMP"
        fixDataTypeMismatches: "No"
  variables:
    silver_database:
      metadata:
        type: "TEXT"
        description: "Silver layer database name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    silver_schema:
      metadata:
        type: "TEXT"
        description: "Silver layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SILVER"
    gold_database:
      metadata:
        type: "TEXT"
        description: "Gold layer database name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    gold_schema:
      metadata:
        type: "TEXT"
        description: "Gold layer schema name"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "GOLD"
    watermark_default:
      metadata:
        type: "TEXT"
        description: "Default watermark for first load"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1900-01-01"
design:
  components:
    Write to FACT_CAMPAIGN_DAILY:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
    Incremental Load and Aggregate:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
  notes:
    "1":
      position:
        x: -100
        "y": -460
      size:
        height: 460
        width: 400
      theme: "yellow"
      content: |
        ### FACT_CAMPAIGN_DAILY (Pre-Aggregated)

        **Load Strategy**: Incremental with watermark
        **Grain**: Campaign/Day

        **Source**: MTLN_SILVER_PERFORMANCE
        **Watermark**: LOAD_TIMESTAMP

        **Aggregations**:
        - SUM: Impressions, Clicks, Conversions, Cost, Revenue
        - AVG: CTR, CPC
        - CALC: Total ROAS, Channel Count

        **Use Case**: Fast campaign performance dashboards
        **Performance**: 99% faster queries vs raw fact table
