type: "orchestration"
version: "1.0"
pipeline:
  metadata:
    description: "Smart SCD Type 2 - Runs Initial Load if empty, otherwise Incremental"
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
          - "Check Table Row Count"
      parameters:
        componentName: "Start"
    Check Table Row Count:
      type: "query-to-scalar"
      transitions:
        success:
          - "Is Table Empty"
      parameters:
        componentName: "Check Table Row Count"
        mode: "Advanced"
        query: |
          SELECT COUNT(*) 
          FROM ${gold_database}.${gold_schema}.DIM_CUSTOMER
        scalarVariableMapping:
          - - "table_row_count"
            - "COUNT(*)"
    Is Table Empty:
      type: "if"
      transitions:
        "true":
          - "Run Initial Load"
        "false":
          - "Run Incremental SCD Type 2"
      parameters:
        componentName: "Is Table Empty"
        mode: "Simple"
        condition:
          - - "table_row_count"
            - "Is"
            - "Equal to"
            - "0"
        combineConditions: "And"
    Run Initial Load:
      type: "run-transformation"
      parameters:
        componentName: "Run Initial Load"
        transformationJob: "Silver to Gold/Silver to Gold - DIM_CUSTOMER (Initial Load).tran.yaml"
        setScalarVariables:
          - - "gold_schema"
            - "${gold_schema}"
    Run Incremental SCD Type 2:
      type: "run-transformation"
      parameters:
        componentName: "Run Incremental SCD Type 2"
        transformationJob: "Silver to Gold/Silver to Gold - DIM_CUSTOMER.tran.yaml"
        setScalarVariables:
          - - "gold_schema"
            - "${gold_schema}"
  variables:
    gold_database:
      metadata:
        type: "TEXT"
        description: "Gold layer database"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "MATILLION_DB"
    gold_schema:
      metadata:
        type: "TEXT"
        description: "Gold layer schema"
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "GOLD"
    table_row_count:
      metadata:
        type: "NUMBER"
        description: "Row count from DIM_CUSTOMER - used for conditional logic"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "0"
design:
  components:
    Start:
      position:
        x: 0
        y: 0
    Check Table Row Count:
      position:
        x: 160
        y: 0
    Is Table Empty:
      position:
        x: 320
        y: 0
    Run Initial Load:
      position:
        x: 480
        y: -60
    Run Incremental SCD Type 2:
      position:
        x: 480
        y: 60
  notes:
    "1":
      position:
        x: -10
        y: -561
      size:
        height: 470
        width: 680
      theme: "light-green"
      content: |
        ### Smart SCD Type 2 - DIM_CUSTOMER (Conditional Logic)
        
        **PURPOSE**: Automatically chooses Initial vs Incremental load
        **RUN**: Anytime (safe for first run or daily runs)
        
        **Logic Flow**:
        1. **Query to Scalar** - Counts rows in DIM_CUSTOMER
        2. **If Component** - Evaluates: Is row count = 0?
        
        **If TRUE (table empty)**:
        → Run "Initial Load" pipeline
        → Loads all records with VERSION=1, IS_CURRENT=TRUE
        
        **If FALSE (table has data)**:
        → Run "Incremental SCD Type 2" pipeline  
        → Detect Changes + Insert new versions
        
        **Result**: One pipeline handles both scenarios!
