-- =====================================================
-- MASTER DDL SCRIPT - CREATE ALL DATABASE OBJECTS
-- Purpose: Complete schema and table creation for Medallion Architecture
-- Execution Order: Schemas → Bronze → Silver → Gold (Dimensions → Facts)
-- =====================================================

-- =====================================================
-- STEP 1: CREATE DATABASE AND SCHEMAS
-- =====================================================

-- Create Database (if not exists)
CREATE DATABASE IF NOT EXISTS MATILLION_DB;
USE DATABASE MATILLION_DB;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS BRONZE COMMENT = 'Bronze Layer: Raw/Landing zone - as-is from source';
CREATE SCHEMA IF NOT EXISTS SILVER COMMENT = 'Silver Layer: Cleansed and validated data';
CREATE SCHEMA IF NOT EXISTS GOLD COMMENT = 'Gold Layer: Analytics-ready dimension and fact tables';

-- =====================================================
-- STEP 2: BRONZE LAYER TABLES (6 tables)
-- =====================================================

-- Execute: Bronze - Create All Tables.sql
-- Tables: MTLN_BRONZE_CAMPAIGNS, MTLN_BRONZE_CHANNELS, MTLN_BRONZE_CUSTOMERS,
--         MTLN_BRONZE_PERFORMANCE, MTLN_BRONZE_PRODUCTS, MTLN_BRONZE_SALES

USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE MTLN_BRONZE_CAMPAIGNS (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM'
) COMMENT = 'Bronze: Marketing campaigns - as-is from source';

CREATE OR REPLACE TABLE MTLN_BRONZE_CHANNELS (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM'
) COMMENT = 'Bronze: Marketing channels - as-is from source';

CREATE OR REPLACE TABLE MTLN_BRONZE_CUSTOMERS (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CRM'
) COMMENT = 'Bronze: Customer master data - as-is from source';

CREATE OR REPLACE TABLE MTLN_BRONZE_PERFORMANCE (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM'
) COMMENT = 'Bronze: Marketing performance metrics - as-is from source';

CREATE OR REPLACE TABLE MTLN_BRONZE_PRODUCTS (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ERP'
) COMMENT = 'Bronze: Product catalog - as-is from source';

CREATE OR REPLACE TABLE MTLN_BRONZE_SALES (
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ERP'
) COMMENT = 'Bronze: Sales transactions - as-is from source';

-- =====================================================
-- STEP 3: SILVER LAYER TABLES (6 tables)
-- =====================================================

-- Execute: Silver - Create All Tables.sql
-- Tables: MTLN_SILVER_CAMPAIGNS, MTLN_SILVER_CHANNELS, MTLN_SILVER_CUSTOMERS,
--         MTLN_SILVER_PERFORMANCE, MTLN_SILVER_PRODUCTS, MTLN_SILVER_SALES

USE SCHEMA SILVER;

CREATE OR REPLACE TABLE MTLN_SILVER_CAMPAIGNS (
    CAMPAIGN_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CAMPAIGN_NAME VARCHAR(200),
    CAMPAIGN_TYPE VARCHAR(50),
    STATUS VARCHAR(50),
    OBJECTIVE VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    BUDGET NUMBER(18,2),
    DURATION_DAYS NUMBER(10,0),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM',
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Silver: Marketing campaigns with data cleansing and quality checks';

CREATE OR REPLACE TABLE MTLN_SILVER_CHANNELS (
    CHANNEL_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CHANNEL_NAME VARCHAR(100),
    CHANNEL_TYPE VARCHAR(50),
    CATEGORY VARCHAR(50),
    COST_STRUCTURE VARCHAR(50),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM',
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Silver: Marketing channels with data cleansing';

CREATE OR REPLACE TABLE MTLN_SILVER_CUSTOMERS (
    CUSTOMER_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SEGMENT VARCHAR(50),
    TIER VARCHAR(50),
    STATUS VARCHAR(50),
    REGISTRATION_DATE DATE,
    LIFETIME_VALUE NUMBER(18,2),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'CRM',
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Silver: Customer master data with data cleansing';

CREATE OR REPLACE TABLE MTLN_SILVER_PERFORMANCE (
    PERFORMANCE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(100),
    CHANNEL_ID VARCHAR(100),
    PERFORMANCE_DATE DATE NOT NULL,
    IMPRESSIONS NUMBER(18,0) DEFAULT 0,
    CLICKS NUMBER(18,0) DEFAULT 0,
    COST NUMBER(18,2) DEFAULT 0,
    CONVERSIONS NUMBER(18,0) DEFAULT 0,
    REVENUE NUMBER(18,2) DEFAULT 0,
    CTR NUMBER(10,4),
    CPC NUMBER(18,4),
    CPA NUMBER(18,4),
    ROAS NUMBER(10,4),
    CONVERSION_RATE NUMBER(10,4),
    CLICKS_VALID BOOLEAN,
    CONVERSIONS_VALID BOOLEAN,
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'AD_PLATFORM'
) COMMENT = 'Silver: Marketing performance with calculated KPIs';

CREATE OR REPLACE TABLE MTLN_SILVER_PRODUCTS (
    PRODUCT_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    SKU VARCHAR(100),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRODUCT_STATUS VARCHAR(50),
    UNIT_PRICE NUMBER(18,2),
    COST NUMBER(18,2),
    MARGIN NUMBER(18,2),
    MARGIN_PERCENT NUMBER(10,2),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ERP',
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Silver: Product catalog with calculated metrics';

CREATE OR REPLACE TABLE MTLN_SILVER_SALES (
    ORDER_LINE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ORDER_ID VARCHAR(100),
    CUSTOMER_ID VARCHAR(100),
    PRODUCT_ID VARCHAR(100),
    ORDER_DATE DATE,
    QUANTITY NUMBER(10,0),
    UNIT_PRICE NUMBER(18,2),
    DISCOUNT_PERCENT NUMBER(5,2),
    LINE_TOTAL NUMBER(18,2),
    TAX NUMBER(18,2),
    SHIPPING_COST NUMBER(18,2),
    GRAND_TOTAL NUMBER(18,2),
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ERP',
    LAST_MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Silver: Sales transactions with calculated metrics';

-- =====================================================
-- STEP 4: GOLD LAYER - DIMENSION TABLES (5 tables)
-- =====================================================

-- Execute: Gold - Create Dimensions.sql
-- Tables: DIM_DATE, DIM_PRODUCT, DIM_CUSTOMER, DIM_CAMPAIGN, DIM_CHANNEL

USE SCHEMA GOLD;

-- DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER(8,0) NOT NULL PRIMARY KEY,
    DATE_VALUE DATE NOT NULL,
    YEAR NUMBER(4,0),
    QUARTER NUMBER(1,0),
    QUARTER_NAME VARCHAR(10),
    MONTH NUMBER(2,0),
    MONTH_NAME VARCHAR(20),
    MONTH_SHORT_NAME VARCHAR(3),
    WEEK_OF_YEAR NUMBER(2,0),
    DAY_OF_YEAR NUMBER(3,0),
    DAY_OF_MONTH NUMBER(2,0),
    DAY_OF_WEEK NUMBER(1,0),
    DAY_NAME VARCHAR(20),
    DAY_SHORT_NAME VARCHAR(3),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    HOLIDAY_NAME VARCHAR(100),
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    FISCAL_MONTH NUMBER(2,0)
) COMMENT = 'Gold: Date dimension for time-series analysis (2020-2030)';

-- DIM_PRODUCT (SCD Type 1)
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER(18,0) AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR(100) NOT NULL UNIQUE,
    SKU VARCHAR(100),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRODUCT_STATUS VARCHAR(50),
    UNIT_PRICE NUMBER(18,2),
    COST NUMBER(18,2),
    MARGIN NUMBER(18,2),
    MARGIN_PERCENT NUMBER(10,2),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    SOURCE_SYSTEM VARCHAR(50)
) COMMENT = 'Gold: Product dimension with SCD Type 1 (overwrite changes)';

-- DIM_CUSTOMER (SCD Type 2)
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER(18,0) AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    CUSTOMER_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SEGMENT VARCHAR(50),
    TIER VARCHAR(50),
    STATUS VARCHAR(50),
    REGISTRATION_DATE DATE,
    LIFETIME_VALUE NUMBER(18,2),
    SOURCE_SYSTEM VARCHAR(50),
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    VALID_TO TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE NOT NULL,
    VERSION_NUMBER NUMBER(10,0) DEFAULT 1 NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Gold: Customer dimension with SCD Type 2 for tracking segment/tier changes';

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_CURRENT ON DIM_CUSTOMER(CUSTOMER_ID, IS_CURRENT);

-- DIM_CAMPAIGN (SCD Type 2)
CREATE OR REPLACE TABLE DIM_CAMPAIGN (
    CAMPAIGN_KEY NUMBER(18,0) AUTOINCREMENT PRIMARY KEY,
    CAMPAIGN_ID VARCHAR(100) NOT NULL,
    CAMPAIGN_NAME VARCHAR(200),
    CAMPAIGN_TYPE VARCHAR(50),
    STATUS VARCHAR(50),
    OBJECTIVE VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    BUDGET NUMBER(18,2),
    DURATION_DAYS NUMBER(10,0),
    SOURCE_SYSTEM VARCHAR(50),
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    VALID_TO TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE NOT NULL,
    VERSION_NUMBER NUMBER(10,0) DEFAULT 1 NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
) COMMENT = 'Gold: Campaign dimension with SCD Type 2 for tracking budget/status changes';

CREATE INDEX IF NOT EXISTS IDX_CAMPAIGN_CURRENT ON DIM_CAMPAIGN(CAMPAIGN_ID, IS_CURRENT);

-- DIM_CHANNEL (SCD Type 3)
CREATE OR REPLACE TABLE DIM_CHANNEL (
    CHANNEL_KEY NUMBER(18,0) AUTOINCREMENT PRIMARY KEY,
    CHANNEL_ID VARCHAR(100) NOT NULL UNIQUE,
    CHANNEL_NAME VARCHAR(100),
    CHANNEL_TYPE VARCHAR(50),
    CURRENT_CATEGORY VARCHAR(50),
    COST_STRUCTURE VARCHAR(50),
    PREVIOUS_CATEGORY VARCHAR(50),
    CATEGORY_CHANGED_DATE DATE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    SOURCE_SYSTEM VARCHAR(50)
) COMMENT = 'Gold: Channel dimension with SCD Type 3 for category change tracking';

-- =====================================================
-- STEP 5: GOLD LAYER - FACT TABLES (3 tables)
-- =====================================================

-- Execute: Gold - Create Facts.sql
-- Tables: FACT_PERFORMANCE, FACT_SALES, FACT_CAMPAIGN_DAILY

-- FACT_PERFORMANCE
CREATE OR REPLACE TABLE FACT_PERFORMANCE (
    PERFORMANCE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CAMPAIGN_KEY NUMBER(18,0) NOT NULL,
    CHANNEL_KEY NUMBER(18,0) NOT NULL,
    DATE_KEY NUMBER(8,0) NOT NULL,
    IMPRESSIONS NUMBER(18,0) DEFAULT 0,
    CLICKS NUMBER(18,0) DEFAULT 0,
    CONVERSIONS NUMBER(18,0) DEFAULT 0,
    COST NUMBER(18,2) DEFAULT 0,
    REVENUE NUMBER(18,2) DEFAULT 0,
    CTR NUMBER(10,4),
    CPC NUMBER(18,4),
    CPA NUMBER(18,4),
    ROAS NUMBER(10,4),
    CONVERSION_RATE NUMBER(10,4),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    SOURCE_SYSTEM VARCHAR(50)
) CLUSTER BY (DATE_KEY, CAMPAIGN_KEY)
COMMENT = 'Gold: Marketing performance fact table - daily grain';

-- FACT_SALES
CREATE OR REPLACE TABLE FACT_SALES (
    ORDER_LINE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    ORDER_ID VARCHAR(100) NOT NULL,
    CUSTOMER_KEY NUMBER(18,0) NOT NULL,
    PRODUCT_KEY NUMBER(18,0) NOT NULL,
    DATE_KEY NUMBER(8,0) NOT NULL,
    QUANTITY NUMBER(10,0),
    UNIT_PRICE NUMBER(18,2),
    DISCOUNT_PERCENT NUMBER(5,2),
    LINE_TOTAL NUMBER(18,2),
    TAX NUMBER(18,2),
    SHIPPING_COST NUMBER(18,2),
    GRAND_TOTAL NUMBER(18,2),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    SOURCE_SYSTEM VARCHAR(50)
) CLUSTER BY (DATE_KEY, CUSTOMER_KEY)
COMMENT = 'Gold: Sales fact table - order line grain';

-- FACT_CAMPAIGN_DAILY
CREATE OR REPLACE TABLE FACT_CAMPAIGN_DAILY (
    CAMPAIGN_KEY NUMBER(18,0) NOT NULL,
    DATE_KEY NUMBER(8,0) NOT NULL,
    TOTAL_IMPRESSIONS NUMBER(18,0) DEFAULT 0,
    TOTAL_CLICKS NUMBER(18,0) DEFAULT 0,
    TOTAL_CONVERSIONS NUMBER(18,0) DEFAULT 0,
    TOTAL_COST NUMBER(18,2) DEFAULT 0,
    TOTAL_REVENUE NUMBER(18,2) DEFAULT 0,
    AVG_CTR NUMBER(10,4),
    AVG_CPC NUMBER(18,4),
    TOTAL_ROAS NUMBER(10,4),
    CHANNEL_COUNT NUMBER(10,0),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY (CAMPAIGN_KEY, DATE_KEY)
) CLUSTER BY (DATE_KEY)
COMMENT = 'Gold: Pre-aggregated campaign performance by day';

-- =====================================================
-- STEP 6: VERIFICATION - LIST ALL CREATED OBJECTS
-- =====================================================

SELECT 'BRONZE TABLES' AS LAYER, TABLE_NAME, ROW_COUNT, COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'BRONZE' AND TABLE_NAME LIKE 'MTLN_%'
UNION ALL
SELECT 'SILVER TABLES' AS LAYER, TABLE_NAME, ROW_COUNT, COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME LIKE 'MTLN_%'
UNION ALL
SELECT 'GOLD DIMENSIONS' AS LAYER, TABLE_NAME, ROW_COUNT, COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME LIKE 'DIM_%'
UNION ALL
SELECT 'GOLD FACTS' AS LAYER, TABLE_NAME, ROW_COUNT, COMMENT 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME LIKE 'FACT_%'
ORDER BY LAYER, TABLE_NAME;

-- =====================================================
-- COMPLETION MESSAGE
-- =====================================================

SELECT '✅ ALL DDL OBJECTS CREATED SUCCESSFULLY!' AS STATUS,
       (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'BRONZE' AND TABLE_NAME LIKE 'MTLN_%') AS BRONZE_TABLES,
       (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME LIKE 'MTLN_%') AS SILVER_TABLES,
       (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME LIKE 'DIM_%') AS GOLD_DIMENSIONS,
       (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'GOLD' AND TABLE_NAME LIKE 'FACT_%') AS GOLD_FACTS;