-- =====================================================
-- GRANTS AND PRIVILEGES - MATILLION_ROLE
-- Purpose: Complete privilege setup for Matillion ETL operations
-- Medallion Architecture: Bronze → Silver → Gold
-- =====================================================

-- =====================================================
-- STEP 1: CREATE ROLE (if not exists)
-- =====================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS MATILLION_ROLE
    COMMENT = 'Role for Matillion ETL operations - Full access to Bronze, Silver, Gold layers';

-- =====================================================
-- STEP 2: GRANT ROLE TO USERS
-- =====================================================
-- Replace 'MATILLION_USER' with actual Matillion service account username

GRANT ROLE MATILLION_ROLE TO USER MATILLION_USER;
-- Grant to additional users if needed:
-- GRANT ROLE MATILLION_ROLE TO USER DATA_ENGINEER_1;
-- GRANT ROLE MATILLION_ROLE TO USER DATA_ENGINEER_2;

-- =====================================================
-- STEP 3: DATABASE LEVEL PRIVILEGES
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- Grant database usage
GRANT USAGE ON DATABASE MATILLION_DB TO ROLE MATILLION_ROLE;

-- Grant ability to create schemas (if needed)
GRANT CREATE SCHEMA ON DATABASE MATILLION_DB TO ROLE MATILLION_ROLE;

-- Grant monitor privileges for performance tracking
GRANT MONITOR ON DATABASE MATILLION_DB TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 4: WAREHOUSE PRIVILEGES
-- =====================================================
-- Grant warehouse usage for ETL operations
-- Replace 'COMPUTE_WH' with your actual warehouse name(s)

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MATILLION_ROLE;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE MATILLION_ROLE;
GRANT MONITOR ON WAREHOUSE COMPUTE_WH TO ROLE MATILLION_ROLE;

-- Optional: Grant MODIFY to allow Matillion to suspend/resume warehouse
-- GRANT MODIFY ON WAREHOUSE COMPUTE_WH TO ROLE MATILLION_ROLE;

-- If you have separate warehouses for different layers:
-- GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE MATILLION_ROLE;
-- GRANT OPERATE ON WAREHOUSE ETL_WH TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 5: BRONZE SCHEMA PRIVILEGES
-- =====================================================

USE DATABASE MATILLION_DB;

-- Schema-level privileges
GRANT USAGE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE TABLE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE VIEW ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE STAGE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE FUNCTION ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT MONITOR ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- Table-level privileges (ALL TABLES - current and future)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- View privileges
GRANT SELECT ON ALL VIEWS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- Stage privileges (for data loading)
GRANT READ, WRITE ON ALL STAGES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- File Format privileges
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- Sequence privileges
GRANT USAGE ON ALL SEQUENCES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- Function/Procedure privileges
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA BRONZE TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 6: SILVER SCHEMA PRIVILEGES
-- =====================================================

-- Schema-level privileges
GRANT USAGE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE TABLE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE VIEW ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE STAGE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE FUNCTION ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT MONITOR ON SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- Table-level privileges (ALL TABLES - current and future)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- View privileges
GRANT SELECT ON ALL VIEWS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- Stage privileges
GRANT READ, WRITE ON ALL STAGES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- File Format privileges
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- Sequence privileges
GRANT USAGE ON ALL SEQUENCES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- Function/Procedure privileges
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SILVER TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 7: GOLD SCHEMA PRIVILEGES
-- =====================================================

-- Schema-level privileges
GRANT USAGE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE TABLE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE VIEW ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE STAGE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE FUNCTION ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT MONITOR ON SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Table-level privileges (ALL TABLES - current and future)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- View privileges
GRANT SELECT ON ALL VIEWS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Stage privileges
GRANT READ, WRITE ON ALL STAGES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- File Format privileges
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Sequence privileges
GRANT USAGE ON ALL SEQUENCES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Function/Procedure privileges
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 8: ADDITIONAL PRIVILEGES (Optional)
-- =====================================================

-- Grant ability to create temporary tables (useful for ETL)
GRANT CREATE TEMPORARY TABLE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE TEMPORARY TABLE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE TEMPORARY TABLE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Grant ability to use dynamic tables (if using Snowflake Dynamic Tables)
-- GRANT CREATE DYNAMIC TABLE ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
-- GRANT CREATE DYNAMIC TABLE ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
-- GRANT CREATE DYNAMIC TABLE ON SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- Grant ability to create materialized views
GRANT CREATE MATERIALIZED VIEW ON SCHEMA BRONZE TO ROLE MATILLION_ROLE;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA SILVER TO ROLE MATILLION_ROLE;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA GOLD TO ROLE MATILLION_ROLE;

-- =====================================================
-- STEP 9: VERIFICATION QUERIES
-- =====================================================

-- View all grants for MATILLION_ROLE
SHOW GRANTS TO ROLE MATILLION_ROLE;

-- View users assigned to MATILLION_ROLE
SHOW GRANTS OF ROLE MATILLION_ROLE;

-- Verify database grants
SHOW GRANTS ON DATABASE MATILLION_DB;

-- Verify schema grants
SHOW GRANTS ON SCHEMA BRONZE;
SHOW GRANTS ON SCHEMA SILVER;
SHOW GRANTS ON SCHEMA GOLD;

-- Test query to verify SELECT access
USE ROLE MATILLION_ROLE;
SELECT 'BRONZE' AS LAYER, COUNT(*) AS TABLE_COUNT 
FROM MATILLION_DB.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'BRONZE'
UNION ALL
SELECT 'SILVER', COUNT(*) 
FROM MATILLION_DB.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'SILVER'
UNION ALL
SELECT 'GOLD', COUNT(*) 
FROM MATILLION_DB.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'GOLD';

-- =====================================================
-- PRIVILEGE SUMMARY
-- =====================================================
/*
MATILLION_ROLE has been granted:

DATABASE LEVEL:
✅ USAGE on MATILLION_DB
✅ CREATE SCHEMA
✅ MONITOR

WAREHOUSE LEVEL:
✅ USAGE on COMPUTE_WH
✅ OPERATE on COMPUTE_WH
✅ MONITOR on COMPUTE_WH

SCHEMA LEVEL (Bronze, Silver, Gold):
✅ USAGE
✅ CREATE TABLE, VIEW, STAGE, FILE FORMAT, SEQUENCE, FUNCTION, PROCEDURE
✅ CREATE TEMPORARY TABLE
✅ CREATE MATERIALIZED VIEW
✅ MONITOR

TABLE LEVEL (Current and Future):
✅ SELECT
✅ INSERT
✅ UPDATE
✅ DELETE
✅ TRUNCATE

VIEW LEVEL (Current and Future):
✅ SELECT

STAGE LEVEL (Current and Future):
✅ READ
✅ WRITE

OTHER OBJECTS (Current and Future):
✅ USAGE on FILE FORMATS, SEQUENCES, FUNCTIONS, PROCEDURES

KEY FEATURES:
- FUTURE grants ensure new objects inherit privileges
- Full CRUD operations on all tables
- Ability to create and manage database objects
- Read/Write access to stages for data loading
- Complete ETL pipeline permissions
*/

-- =====================================================
-- ADDITIONAL ROLES (Optional - for different access levels)
-- =====================================================

-- Create read-only analyst role
/*
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Read-only access to Gold layer for analysts';

USE ROLE ACCOUNTADMIN;

-- Grant database and warehouse usage
GRANT USAGE ON DATABASE MATILLION_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;

-- Grant read-only access to Gold schema
GRANT USAGE ON SCHEMA GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOLD TO ROLE ANALYST_ROLE;

-- Assign to analyst users
GRANT ROLE ANALYST_ROLE TO USER ANALYST_1;
GRANT ROLE ANALYST_ROLE TO USER ANALYST_2;
*/

-- =====================================================
-- REVOKE PRIVILEGES (if needed)
-- =====================================================
/*
-- To revoke all privileges from MATILLION_ROLE:
USE ROLE ACCOUNTADMIN;

REVOKE ALL PRIVILEGES ON SCHEMA BRONZE FROM ROLE MATILLION_ROLE;
REVOKE ALL PRIVILEGES ON SCHEMA SILVER FROM ROLE MATILLION_ROLE;
REVOKE ALL PRIVILEGES ON SCHEMA GOLD FROM ROLE MATILLION_ROLE;
REVOKE ALL PRIVILEGES ON DATABASE MATILLION_DB FROM ROLE MATILLION_ROLE;
REVOKE USAGE ON WAREHOUSE COMPUTE_WH FROM ROLE MATILLION_ROLE;

-- To drop the role entirely:
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS MATILLION_ROLE;
*/

-- =====================================================
-- COMPLETION MESSAGE
-- =====================================================

SELECT '✅ ALL PRIVILEGES GRANTED TO MATILLION_ROLE SUCCESSFULLY!' AS STATUS,
       'Run "SHOW GRANTS TO ROLE MATILLION_ROLE" to verify' AS NEXT_STEP;